name: Submit dependency graph

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
